version: '3'
services:
  app:
    build:
      context: '.'
    image: 'mozamimy/bts-bot'
    environment:
      CLIENT_ID:
      SECRET_TOKEN:
    container_name: 'bts-bot-app'
    command: ["bundle", "exec", "exe/bts_bot"]
