iokuji:
  - subject: '大凶'
    body: '何もないところで転んだり自動ドアに挟まったりしそう！身近にある死亡フラグに気をつけて！'
  - subject: '大凶'
    body: '身近な人からの心無い一言で傷つきそう.. 明るく前向きに！'
  - subject: '凶'
    body: 'さわやかな笑顔が一日を楽しく過ごすコツ！'
  - subject: '凶'
    body: '舌にどうしてもとれない髪の毛がついてしまうなどの微妙にイライラする出来事がありそう！'
  - subject: '末吉'
    body: '今日は一日平穏に過ごせそう🐰✨'
  - subject: '末吉'
    body: 'いつもどおりに過ごすのが一日を平穏に過ごすコツ！'
  - subject: '中吉'
    body: 'ちょっとしたいいことがありそう！自動販売機のおつりの出てくるところや地面との隙間に注目してみて。'
  - subject: '中吉'
    body: 'ちょっとした褒められが発生して承認欲求が満たされそう！控えめに自己アピールしてね。'
  - subject: '大吉'
    body: '5 億円が当たるチャンス到来⁉️'
  - subject: '大吉'
    body: '何をやってもうまくいく全能感に酔いしれそう🐴'
  - subject: '👁 👁'
    body: 'ｽﾞｯﾄ ｵﾏｴｦ ﾐﾃｲﾙｿﾞ...'
